### ISSUE TITLE
Licensing?

### ISSUE THREAD

**Issue by jayaddison** [openfoodbroker/pynutrition#1]
I'm very keen to try this software and would love to incorporate [meal-plan-solving](https://github.com/openculinary/frontend/blob/940f4c6a0da1f915f5ded73d28fe65b480838157/src/index.html#L209) into the RecipeRadar frontend application in future.

Could I ask what kind of software usage license might be planned for `pynutrition`?

Thanks!

**Comment by synergiator** [comment]
hi there @jayaddison , thanks raising this, indeed I've forgot the license file! Now it's included - MIT license.

Looking forward to your feedback!

**Comment by jayaddison** [comment]
No worries, thanks for confirming!  I'll aim to take a look at the project in more detail soon.
